###GET
GET http://localhost:8081/teste/users

###POST
POST http://localhost:8081/teste/criar
Content-Type: application/json

{
    "nome" : "",
    "cpf" : "77777777777",
    "endereco" : "casa",
    "email" : "",
    "senha" : ""
}